### ISSUE TITLE
Please clarify licenses

### ISSUE THREAD

**Issue by musicinmybrain** [Donders-Institute/multiecho#15]
Can you please clarify whether [`LICENSE-APACHE`](https://github.com/Donders-Institute/multiecho/blob/0.28/LICENSE-APACHE) and [`LICENSE-MIT`](https://github.com/Donders-Institute/multiecho/blob/0.28/LICENSE-MIT) are intended to be applied conjunctively (both) or disjunctively (either)?

That is, in SPDX terms, which of the following is correct?

- [`Apache-2.0`](https://spdx.org/licenses/Apache-2.0.html)` AND `[`MIT`](https://spdx.org/licenses/MIT.html)
- [`Apache-2.0`](https://spdx.org/licenses/Apache-2.0.html)` OR `[`MIT`](https://spdx.org/licenses/MIT.html)

I suspect the latter was intended, but I can’t find anything in the source that makes this explicit.

**Comment by marcelzwiers** [comment]
Hello again, thanks for your contributions, I really appreciate them. The multiecho package was developed by @dangom and I took over ownership after Daniel left for Boston. But I don't really actively develop it unless there is a need to (which hasn't been the case for a while now). I've now clarified the license to be `Apache-2.0 OR MIT`
