### ISSUE TITLE
Interest in maintaining a man page?

### ISSUE THREAD

**Issue by musicinmybrain** [Donders-Institute/multiecho#18]
I’m preparing to package this for Fedora Linux as a dependency for https://github.com/Donders-Institute/bidscoin.

We always [like to have man pages](https://docs.fedoraproject.org/en-US/packaging-guidelines/#_manpages) for executables when possible. Sometimes [help2man](https://www.gnu.org/software/help2man/) can generate something decent. In this case, the result would be mostly legible, but it doesn’t do a great job with the examples. I plan to use the `--help` output of `mecombine` to write a man page in `groff_man(7)` format by hand.

Is there any interest in keeping such a man page upstream? The Python ecosystem doesn’t really have a way to install man pages, but shipping a man page in the sdist would make it available to other distribution packagers, at least.

If this is of interest, I’m happy to offer a PR adding a man page `mecombine.1` in the top-level directory and adding it to `MANIFEST.in`. Otherwise, I’ll just maintain the man page downstream.

**Comment by marcelzwiers** [comment]
That sounds great and that's certainly an incentive for me to bring the multiecho library up to standards. Any PR is of course more than welcome :-).

**Comment by marcelzwiers** [comment]
Is this of any use? I've never build manpages, but it seems to convert python's argparse arguments to a manpage?

**Comment by musicinmybrain** [comment]
> Is this of any use? I've never build manpages, but it seems to convert python's argparse arguments to a manpage? https://pypi.org/project/argparse-manpage/

Hmm, it might be! I’ll take a look at it and see if it’s easy to incorporate. It’s always nice to reduce duplication.

**Comment by marcelzwiers** [comment]
I think Arch and Ubuntu use it also... (see e.g. https://man.archlinux.org/man/argparse-manpage.1.en)
